<?php
add_action(
	'acf/include_fields',
	function() {
		if ( ! function_exists( 'acf_add_local_field_group' ) ) {
			return;
		}

		acf_add_local_field_group(
			array(
				'key'                   => 'group_65ccc6aa66ec8',
				'title'                 => 'Single Chart Page Fields',
				'fields'                => array(
					array(
						'key'               => 'field_65cdf1a5cd683',
						'label'             => 'Chart',
						'name'              => 'chart',
						'aria-label'        => '',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'block',
						'sub_fields'        => array(
							array(
								'key'               => 'field_65cdf1a5cd684',
								'label'             => 'Title',
								'name'              => 'title',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
							),
							array(
								'key'               => 'field_65cdf1a5cd685',
								'label'             => 'Legends',
								'name'              => 'legends',
								'aria-label'        => '',
								'type'              => 'group',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'layout'            => 'table',
								'sub_fields'        => array(
									array(
										'key'           => 'field_65cdf1a5cd686',
										'label'         => 'Legend1',
										'name'          => 'legend1',
										'aria-label'    => '',
										'type'          => 'text',
										'instructions'  => '',
										'required'      => 0,
										'conditional_logic' => 0,
										'wrapper'       => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value' => '',
										'maxlength'     => '',
										'placeholder'   => '',
										'prepend'       => '',
										'append'        => '',
									),
									array(
										'key'           => 'field_65cdf1a5cd687',
										'label'         => 'Legend2',
										'name'          => 'legend2',
										'aria-label'    => '',
										'type'          => 'text',
										'instructions'  => '',
										'required'      => 0,
										'conditional_logic' => 0,
										'wrapper'       => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value' => '',
										'maxlength'     => '',
										'placeholder'   => '',
										'prepend'       => '',
										'append'        => '',
									),
								),
							),
							array(
								'key'               => 'field_65cdf1a5cd688',
								'label'             => 'Rows',
								'name'              => 'rows',
								'aria-label'        => '',
								'type'              => 'flexible_content',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'layouts'           => array(
									'layout_65ccc7aa67ac9' => array(
										'key'        => 'layout_65ccc7aa67ac9',
										'name'       => 'row',
										'label'      => 'Row',
										'display'    => 'table',
										'sub_fields' => array(
											array(
												'key'      => 'field_65cdf1a5cd689',
												'label'    => 'Label',
												'name'     => 'label',
												'aria-label' => '',
												'type'     => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper'  => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'maxlength' => '',
												'placeholder' => '',
												'prepend'  => '',
												'append'   => '',
											),
											array(
												'key'      => 'field_65cdf1a5cd68a',
												'label'    => 'Bar1',
												'name'     => 'bar1',
												'aria-label' => '',
												'type'     => 'number',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper'  => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'min'      => '',
												'max'      => '',
												'placeholder' => '',
												'step'     => '',
												'prepend'  => '',
												'append'   => '',
											),
											array(
												'key'      => 'field_65cdf1a5cd68b',
												'label'    => 'Bar2',
												'name'     => 'bar2',
												'aria-label' => '',
												'type'     => 'number',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper'  => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'min'      => '',
												'max'      => '',
												'placeholder' => '',
												'step'     => '',
												'prepend'  => '',
												'append'   => '',
											),
										),
										'min'        => '',
										'max'        => '',
									),
								),
								'min'               => '',
								'max'               => '',
								'button_label'      => 'Add Row',
							),
						),
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'page_template',
							'operator' => '==',
							'value'    => 'page-templates/single-chart.php',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			)
		);

		acf_add_local_field_group(
			array(
				'key'                   => 'group_65d0a55e8e891',
				'title'                 => 'Tabs Page Fields',
				'fields'                => array(
					array(
						'key'               => 'field_65d0a55e9bf15',
						'label'             => 'Tabs',
						'name'              => 'tabs',
						'aria-label'        => '',
						'type'              => 'flexible_content',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layouts'           => array(
							'layout_65ccc6b67143d' => array(
								'key'        => 'layout_65ccc6b67143d',
								'name'       => 'tab',
								'label'      => 'Tab',
								'display'    => 'block',
								'sub_fields' => array(
									array(
										'key'           => 'field_65d0a55ec8c5d',
										'label'         => 'Title',
										'name'          => 'title',
										'aria-label'    => '',
										'type'          => 'text',
										'instructions'  => '',
										'required'      => 0,
										'conditional_logic' => 0,
										'wrapper'       => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value' => '',
										'maxlength'     => '',
										'placeholder'   => '',
										'prepend'       => '',
										'append'        => '',
									),
									array(
										'key'          => 'field_65d0a55ecc813',
										'label'        => 'Chart',
										'name'         => 'chart',
										'aria-label'   => '',
										'type'         => 'group',
										'instructions' => '',
										'required'     => 0,
										'conditional_logic' => 0,
										'wrapper'      => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'layout'       => 'block',
										'sub_fields'   => array(
											array(
												'key'      => 'field_65d0a55ed0275',
												'label'    => 'Title',
												'name'     => 'title',
												'aria-label' => '',
												'type'     => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper'  => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'maxlength' => '',
												'placeholder' => '',
												'prepend'  => '',
												'append'   => '',
											),
											array(
												'key'      => 'field_65d0a55ed3de9',
												'label'    => 'Legends',
												'name'     => 'legends',
												'aria-label' => '',
												'type'     => 'group',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper'  => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'layout'   => 'table',
												'sub_fields' => array(
													array(
														'key'  => 'field_65d0a55edb976',
														'label' => 'Legend1',
														'name' => 'legend1',
														'aria-label' => '',
														'type' => 'text',
														'instructions' => '',
														'required' => 0,
														'conditional_logic' => 0,
														'wrapper' => array(
															'width' => '',
															'class' => '',
															'id' => '',
														),
														'default_value' => '',
														'maxlength' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
													),
													array(
														'key'  => 'field_65d0a55edf5f4',
														'label' => 'Legend2',
														'name' => 'legend2',
														'aria-label' => '',
														'type' => 'text',
														'instructions' => '',
														'required' => 0,
														'conditional_logic' => 0,
														'wrapper' => array(
															'width' => '',
															'class' => '',
															'id' => '',
														),
														'default_value' => '',
														'maxlength' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
													),
												),
											),
											array(
												'key'      => 'field_65d0a55ed7c9a',
												'label'    => 'Rows',
												'name'     => 'rows',
												'aria-label' => '',
												'type'     => 'flexible_content',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper'  => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'layouts'  => array(
													'layout_65ccc7aa67ac9' => array(
														'key'  => 'layout_65ccc7aa67ac9',
														'name' => 'row',
														'label' => 'Row',
														'display' => 'table',
														'sub_fields' => array(
															array(
																'key'  => 'field_65d0a55ee6d5e',
																'label' => 'Label',
																'name' => 'label',
																'aria-label' => '',
																'type' => 'text',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array(
																	'width' => '',
																	'class' => '',
																	'id' => '',
																),
																'default_value' => '',
																'maxlength' => '',
																'placeholder' => '',
																'prepend' => '',
																'append' => '',
															),
															array(
																'key'  => 'field_65d0a55eea7d0',
																'label' => 'Bar1',
																'name' => 'bar1',
																'aria-label' => '',
																'type' => 'number',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array(
																	'width' => '',
																	'class' => '',
																	'id' => '',
																),
																'default_value' => '',
																'min'  => '',
																'max'  => '',
																'placeholder' => '',
																'step' => '',
																'prepend' => '',
																'append' => '',
															),
															array(
																'key'  => 'field_65d0a55eee084',
																'label' => 'Bar2',
																'name' => 'bar2',
																'aria-label' => '',
																'type' => 'number',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array(
																	'width' => '',
																	'class' => '',
																	'id' => '',
																),
																'default_value' => '',
																'min'  => '',
																'max'  => '',
																'placeholder' => '',
																'step' => '',
																'prepend' => '',
																'append' => '',
															),
														),
														'min'  => '',
														'max'  => '',
													),
												),
												'min'      => '',
												'max'      => '',
												'button_label' => 'Add Row',
											),
										),
									),
								),
								'min'        => '',
								'max'        => '',
							),
						),
						'min'               => '',
						'max'               => '',
						'button_label'      => 'Add Tab',
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'page_template',
							'operator' => '==',
							'value'    => 'page-templates/tabs.php',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			)
		);
	}
);

